;;; H2 matching-stage controller v0.1
;;; Matching stage accepts only the fixed training-only fixture.

(defparameter *h2-seeds-primary* '(1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1032))
(defparameter *h2-seeds-replication* '(2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2032))
(defparameter *h2-history* nil)
(defparameter *h2-output-file* nil)
(defparameter *h2-trials* nil)
(defparameter *h2-index* 0)
(defparameter *h2-current-trial* nil)
(defparameter *h2-log* nil)
(defparameter *h2-seed* nil)
(defparameter *h2-ready-time* nil)
(defparameter *h2-required-fixture-name* "H2-W0.3-TRAINING-ONLY.csv")

(defun trim-field (s) (string-trim '(#\Space #\Tab #\Return) s))
(defun split-comma (s)
  (let ((out nil) (start 0))
    (loop for i from 0 to (length s) do
      (when (or (= i (length s)) (char= (char s i) #\,))
        (push (subseq s start i) out)
        (setf start (1+ i))))
    (nreverse out)))
(defun parse-int (s) (parse-integer (trim-field s)))

(defun read-training-fixture (path history)
  (unless (string= (file-namestring (pathname path)) *h2-required-fixture-name*)
    (error "H2 matching boundary violated: unexpected fixture filename."))
  (with-open-file (in path :direction :input)
    (let ((header (read-line in nil nil)) (rows nil))
      (unless header (error "H2 fixture rejected: empty file."))
      (loop for line = (read-line in nil nil) while line do
        (let ((f (split-comma line)))
          (unless (= (length f) 11) (error "H2 fixture rejected: malformed row."))
          (let ((h-name (trim-field (nth 0 f)))
                (phase (string-upcase (trim-field (nth 1 f)))))
            (unless (string= h-name (symbol-name history))
              (error "H2 fixture rejected: history mismatch."))
            (unless (string= phase "TRAINING")
              (error "H2 matching boundary violated: non-training row encountered."))
            (push (list :trial (parse-int (nth 3 f))
                        :c (parse-int (nth 4 f))
                        :x (parse-int (nth 5 f))
                        :y (parse-int (nth 6 f))
                        :correct (intern (string-upcase (trim-field (nth 10 f))) :keyword))
                  rows))))
      (setf rows (nreverse rows))
      (unless (= (length rows) 192)
        (error "H2 fixture rejected: expected 192 training rows, got ~D." (length rows)))
      (loop for row in rows for expected from 1 do
        (unless (= (getf row :trial) expected)
          (error "H2 fixture rejected: trial order not 1..192.")))
      rows)))

(defun h2-rng-state () (no-output (sgp :seed)))
(defun h2-action (state-code action production)
  (declare (ignore state-code))
  (unless *h2-current-trial* (error "H2 action occurred without active trial."))
  (let* ((row (nth (1- *h2-current-trial*) *h2-trials*))
         (truth (getf row :correct))
         (correctness (if (eql action truth) 1 0))
         (rt (- (mp-time) *h2-ready-time*)))
    (push (list :trial *h2-current-trial* :history *h2-history*
                :c (getf row :c) :x (getf row :x) :y (getf row :y)
                :production production :action action :correct-action truth
                :correctness correctness :feedback 1 :rt rt
                :rng-state (h2-rng-state)) *h2-log*)
    (trigger-reward (if (= correctness 1) 1 0))
    (schedule-event-relative 0.001 'h2-finish-trial :maintenance t :priority :min)))

(defun h2-present-row (row)
  (setf *h2-ready-time* (mp-time))
  (goal-focus-fct
   (intern (format nil "G-~D~D~D" (getf row :c) (getf row :x) (getf row :y)) :cl-user)))

(defun h2-write-output ()
  (with-open-file (out *h2-output-file* :direction :output :if-exists :supersede :if-does-not-exist :create)
    (format out "trial,history,c,x,y,production,action,correct_action,correctness,feedback,rt,rng_state~%")
    (dolist (e (reverse *h2-log*))
      (format out "~D,~A,~D,~D,~D,~A,~A,~A,~D,~D,~,9F,~S~%"
              (getf e :trial) (getf e :history) (getf e :c) (getf e :x) (getf e :y)
              (getf e :production) (getf e :action) (getf e :correct-action)
              (getf e :correctness) (getf e :feedback) (getf e :rt) (getf e :rng-state)))))

(defun h2-finish-trial ()
  (if (< *h2-index* (length *h2-trials*))
      (progn (incf *h2-index*)
             (setf *h2-current-trial* *h2-index*)
             (h2-present-row (nth (1- *h2-index*) *h2-trials*)))
      (progn (setf *h2-current-trial* nil)
             (h2-write-output)
             (format t "H2-MATCHING-COMPLETE history=~A seed=~D trials=~D~%" *h2-history* *h2-seed* (length *h2-trials*)))))

(defun run-h2-history-seed (history seed input-file output-file)
  (unless (member history '(H-S H-C)) (error "Unsupported H2 history."))
  (unless (integerp seed) (error "H2 seed must be an integer."))
  (reset)
  (sgp-fct (list :seed (list seed 0)))
  (setf *h2-history* history *h2-output-file* output-file
        *h2-trials* (read-training-fixture input-file history)
        *h2-index* 1 *h2-current-trial* 1 *h2-log* nil *h2-seed* seed *h2-ready-time* nil)
  (h2-present-row (first *h2-trials*))
  (run 5000)
  (unless (null *h2-current-trial*)
    (error "H2 run ended before all training trials completed.")))
